/* tslint:disable */
/* eslint-disable */
/**
 * PrismAgent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateManagedDidRequestDocumentTemplatePublicKeysInner } from './CreateManagedDidRequestDocumentTemplatePublicKeysInner';
import {
    CreateManagedDidRequestDocumentTemplatePublicKeysInnerFromJSON,
    CreateManagedDidRequestDocumentTemplatePublicKeysInnerFromJSONTyped,
    CreateManagedDidRequestDocumentTemplatePublicKeysInnerToJSON,
} from './CreateManagedDidRequestDocumentTemplatePublicKeysInner';
import type { Service } from './Service';
import {
    ServiceFromJSON,
    ServiceFromJSONTyped,
    ServiceToJSON,
} from './Service';

/**
 * 
 * @export
 * @interface CreateManagedDidRequestDocumentTemplate
 */
export interface CreateManagedDidRequestDocumentTemplate {
    /**
     * 
     * @type {Array<CreateManagedDidRequestDocumentTemplatePublicKeysInner>}
     * @memberof CreateManagedDidRequestDocumentTemplate
     */
    publicKeys: Array<CreateManagedDidRequestDocumentTemplatePublicKeysInner>;
    /**
     * 
     * @type {Array<Service>}
     * @memberof CreateManagedDidRequestDocumentTemplate
     */
    services: Array<Service>;
}

/**
 * Check if a given object implements the CreateManagedDidRequestDocumentTemplate interface.
 */
export function instanceOfCreateManagedDidRequestDocumentTemplate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "publicKeys" in value;
    isInstance = isInstance && "services" in value;

    return isInstance;
}

export function CreateManagedDidRequestDocumentTemplateFromJSON(json: any): CreateManagedDidRequestDocumentTemplate {
    return CreateManagedDidRequestDocumentTemplateFromJSONTyped(json, false);
}

export function CreateManagedDidRequestDocumentTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateManagedDidRequestDocumentTemplate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'publicKeys': ((json['publicKeys'] as Array<any>).map(CreateManagedDidRequestDocumentTemplatePublicKeysInnerFromJSON)),
        'services': ((json['services'] as Array<any>).map(ServiceFromJSON)),
    };
}

export function CreateManagedDidRequestDocumentTemplateToJSON(value?: CreateManagedDidRequestDocumentTemplate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'publicKeys': ((value.publicKeys as Array<any>).map(CreateManagedDidRequestDocumentTemplatePublicKeysInnerToJSON)),
        'services': ((value.services as Array<any>).map(ServiceToJSON)),
    };
}

