/* tslint:disable */
/* eslint-disable */
/**
 * PrismAgent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAuthenticationChallengeResponse
 */
export interface CreateAuthenticationChallengeResponse {
    /**
     * A JWT challenge that a user must provide to Castor SDK to create a ChallengeSubmission.
     * JWT payload contains nonce, state, expiration, issuer
     * @type {string}
     * @memberof CreateAuthenticationChallengeResponse
     */
    challenge: string;
    /**
     * A challenged subject that must complete the challenge.
     * May refer to DID or VerificationMethod inside a DID. If VerificationMethod
     * is used, it must be inside the authentication verification relationship.
     * @type {string}
     * @memberof CreateAuthenticationChallengeResponse
     */
    subject?: string;
}

/**
 * Check if a given object implements the CreateAuthenticationChallengeResponse interface.
 */
export function instanceOfCreateAuthenticationChallengeResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "challenge" in value;

    return isInstance;
}

export function CreateAuthenticationChallengeResponseFromJSON(json: any): CreateAuthenticationChallengeResponse {
    return CreateAuthenticationChallengeResponseFromJSONTyped(json, false);
}

export function CreateAuthenticationChallengeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAuthenticationChallengeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'challenge': json['challenge'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
    };
}

export function CreateAuthenticationChallengeResponseToJSON(value?: CreateAuthenticationChallengeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'challenge': value.challenge,
        'subject': value.subject,
    };
}

